apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2  # Number of replicas of your Flask application
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: manohar448/flask-app:latest  # Replace with your Flask app's Docker image
          ports:
            - containerPort: 5000  # Flask app runs on port 5000
         
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80   # External port exposed by the service
      targetPort: 5000   # Port on which the Flask app is listening
  type: LoadBalancer  # Change to ClusterIP if you don't need an external load balancer
